dist: trusty
sudo: required

language:
  - python

python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

before_install:
  - sudo apt-get install --no-install-recommends -y debhelper devscripts libdistro-info-perl libparse-debcontrol-perl python3-all python3-setuptools

script:
  - make deb
