#!/bin/sh
# (c) Reuben Thomas   4th January 2015
# Released under the GPL version 3, or (at your option) any later version.


die(){
    echo "ERROR:${0##*/}: $1" >&2
    exit 1
}


if [ $# -lt 1 ] || ([ $# -eq 1 ] && ([ "$1" = '-h' ] || [ "$1" = '--help' ])); then
    cat <<-EOF
	Usage: ${0##*/} COMMAND [ARGUMENT...]

	Inhibit desktop idleness for the duration of COMMAND
	EOF
    exit 0
fi

wid=$(xwininfo -root | awk '/Window id:/ {print $4}')
if [ -n "$wid" ]; then
    caffeine-screensaver suspend "$wid" || die "failed to inhibit desktop idleness"
    "$@"
    ec=$?
    caffeine-screensaver resume "$wid" || die "failed to uninhibit desktop idleness"
    exit "$ec"
fi
