.TH CAFFEINE "1" "April 2015" "version 0.0.2"
.SH NAME
caffeine \- inhibit desktop idleness in full\-screen mode
.SH SYNOPSIS
.B caffeine
[\fIOPTION\fR]
.SH DESCRIPTION
\fBcaffeine\fR inhibits desktop idleness while an application runs in full-screen
mode, preventing screensavers or power-saving measures from activating even
if the machine is not being used.
.SH OPTIONS
.TP
.BR \-q ", " \-\^\-quiet
Suppress normal output
.TP
.BR \-t ", " \-\^\-timestamp
Timestamp log entries
.TP
.BR \-h ", " \-\^\-help
Show help and exit
.TP
.BR \-V ", " \-\^\-version
Show program's version number and exit
.SH "SEE ALSO"
.PP
\fBcaffeine\-indicator\fR(1),
\fBcaffeinate\fR(1)
.SH AUTHORS
Created by Reuben Thomas <rrt@sc3d.org>.
.PP
Forked by Brian Beffa <brbsix@gmail.com>.
